apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web
  labels:
    type: local
spec:
  storageClassName: cice
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

