version: "3"
services:
  db: #declaracion de la base de datos mysql a dockerizar
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    #declaracion de entorno de la base de datos y los puertos
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"

      #usamos interfaz de admin para la base de datos por el puerto 8080 -80 en del contenedor.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "8080:80"
