--visualiza resultado segun tipo de producto.

SET SERVEROUTPUT ON
DECLARE
 TIPO_PRODUCTO CHAR(1);
BEGIN
 TIPO_PRODUCTO:=UPPER('A');
IF TIPO_PRODUCTO='A' THEN
 DBMS_OUTPUT.PUT_LINE('ELECTRÓNICA');
ELSIF TIPO_PRODUCTO='B' THEN
 DBMS_OUTPUT.PUT_LINE('INFORMÁTICA');
ELSIF TIPO_PRODUCTO='C' THEN
 DBMS_OUTPUT.PUT_LINE('ROPA');
ELSIF TIPO_PRODUCTO='D' THEN
 DBMS_OUTPUT.PUT_LINE('MÚSICA');
ELSIF TIPO_PRODUCTO='E' THEN
 DBMS_OUTPUT.PUT_LINE('LIBRO');
ELSE
 DBMS_OUTPUT.PUT_LINE('EL CÓDIGO ES INCORRECTO');
END IF;
END;